#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

VSTEST_CONSOLE=$(cygpath -au "c:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe")

test -x "$VSTEST_CONSOLE" || exit $?

"$VSTEST_CONSOLE" /inIsolation /Platform:x64 $(cygpath -aw "$TEST_BIN_DIR/ManagedEvalTests.dll") || exit $?
